# Generated by Django 3.2.4 on 2023-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaystackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
    ]
